cmake_minimum_required(VERSION 3.0)

project(SVO-LIB)

set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_SHARED_LIBS ON)
set(GFLAGS_BUILD_SHARED_LIBS ON CACHE BOOL "Build vendored gflags as a shared library." FORCE)
set(GFLAGS_BUILD_STATIC_LIBS OFF CACHE BOOL "Do not build vendored static gflags." FORCE)
set(GFLAGS_BUILD_gflags_LIB ON CACHE BOOL "Build the multi-threaded vendored gflags library." FORCE)
set(GFLAGS_BUILD_gflags_nothreads_LIB OFF CACHE BOOL "Do not build the single-threaded vendored gflags library." FORCE)

add_subdirectory(gflags)
add_subdirectory(glog)
add_subdirectory(fast_neon)
add_subdirectory(minkindr/minkindr)
add_subdirectory(opengv)
add_subdirectory(vikit/vikit_common)
add_subdirectory(vikit/vikit_cameras)
add_subdirectory(vikit/vikit_solver)
add_subdirectory(rpg_common)
add_subdirectory(svo_common)
add_subdirectory(svo_direct)
add_subdirectory(svo_tracker)
add_subdirectory(svo_img_align)
add_subdirectory(svo)
add_subdirectory(svo_env)
